// <auto-generated />
using System;
using DefaultProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefaultProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DefaultProject.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("image");

                    b.Property<string>("name");

                    b.Property<int>("number");

                    b.Property<int?>("ownerid");

                    b.Property<string>("type");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("value");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.ToTable("items");
                });

            modelBuilder.Entity("DefaultProject.Models.Mimic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int>("dex");

                    b.Property<int>("hp");

                    b.Property<int>("hunger");

                    b.Property<string>("image");

                    b.Property<int>("inte");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<int?>("ownerid");

                    b.Property<string>("species");

                    b.Property<int>("str");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.ToTable("mimics");
                });

            modelBuilder.Entity("DefaultProject.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("confirm_password");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<int>("level");

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.Property<string>("username")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DefaultProject.Models.Item", b =>
                {
                    b.HasOne("DefaultProject.Models.User", "owner")
                        .WithMany("items")
                        .HasForeignKey("ownerid");
                });

            modelBuilder.Entity("DefaultProject.Models.Mimic", b =>
                {
                    b.HasOne("DefaultProject.Models.User", "owner")
                        .WithMany("mimics")
                        .HasForeignKey("ownerid");
                });
#pragma warning restore 612, 618
        }
    }
}
